// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When a task template fires.
 *
 * The serialised shape is a contract in three places at once: the
 * `task_templates.cadence` JSONB column, the `cadence_has_known_type` check
 * constraint that guards it, and the ingestion pipeline's generated output.
 * It is defined once, here, so those three cannot drift apart.
 *
 * ```json
 * { "type": "daily" }
 * { "type": "weekly_days", "days": [1, 3, 5] }
 * { "type": "n_per_week", "count": 3 }
 * { "type": "once", "day_offset": 12 }
 * ```
 */
export type Cadence = { "type": "daily" } | { "type": "weekly_days", days: Array<number>, } | { "type": "n_per_week", count: number, } | { "type": "once", day_offset: number, };
