// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClampedField = "difficulty" | "estimated_minutes" | "duration_days" | "day_offset" | "confidence";
