// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratedTask } from "./GeneratedTask";
import type { ProgramKind } from "./ProgramKind";
import type { Warning } from "./Warning";

export type GeneratedProgram = { title: string, summary: string, kind: ProgramKind, duration_days: number, confidence: number, tasks: Array<GeneratedTask>, warnings: Array<Warning>, };
