// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cadence } from "./Cadence";

export type GeneratedTask = { 
/**
 * Imperative, starts with a verb, 80 characters or fewer.
 */
title: string, description: string | null, category: string | null, 
/**
 * 1 to 5.
 */
difficulty: number, 
/**
 * Estimated for a beginner in the domain, not an expert.
 */
estimated_minutes: number, cadence: Cadence, };
