// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of the user's day the program is allowed to claim, per PRD F1.
 */
export type Intensity = "light" | "standard" | "heavy";
