// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClampedField } from "./ClampedField";

/**
 * Something the pipeline guessed at, changed, or could not fix.
 *
 * Warnings carry a **task index, never a task title**. They travel through
 * logs, metrics, and error reporting, and task content is never allowed in any
 * of those. The client resolves the index against the draft it already holds.
 */
export type Warning = { "kind": "day_over_capacity", day_index: number, projected_minutes: number, cap_minutes: number, } | { "kind": "duration_extended", from_days: number, to_days: number, } | { "kind": "task_split", task_index: number, parts: number, } | { "kind": "task_moved", task_index: number, from_day: number, to_day: number, } | { "kind": "empty_day", day_index: number, } | { "kind": "value_clamped", task_index: number | null, field: ClampedField, };
